### ISSUE TITLE
do you think it should be very difficult use different audio file formats?

### ISSUE THREAD

**Issue by manuel-rubio** [sukumo28/wav-preview#1]
I mean, this extension is only valid for wav files, but developing it's possible to find also mp3, ogg and other kinds of formats. Do you think it could be possible to increase the support of this extension by supporting those other extensions?

**Comment by sukumo28** [comment]
If we have an mp3 or ogg decoder that works with VS Code, that's not difficult.  All we have to do is add the `mp3PreviewEditor` and `oggPreviewEditor`.  
In fact, this extension uses an open source wav decoder.  
There are also mp3 and ogg decoders on npm, so if they work with VS Code it may easy to support.  

If the decoder doesn't work, we will have to read the mp3 and ogg specs to write the decoder, which can be a lot of work.

**Comment by sukumo28** [comment]
@manuel-rubio 
mp3, ogg and other kind of formats is supported from v2.0.0
