### ISSUE TITLE
[feature request] allow select progress bar for audio

### ISSUE THREAD

**Issue by Jackiexiao** [sukumo28/wav-preview#2]
![image](https://user-images.githubusercontent.com/18050469/107142330-29e09a00-6969-11eb-89bc-9b2f45a62278.png)

Also, when audio start play,  "play" button should becom "stop" button

thx for create this wonderful plugin!!

**Comment by sukumo28** [comment]
I'll fix it.

**Comment by Jackiexiao** [comment]
thx!
