### ISSUE TITLE
This extension cannot be found in the extensions marketplace of vscode. 

### ISSUE THREAD

**Issue by dqqcasia** [sukumo28/wav-preview#20]
This extension cannot be found in the extensions marketplace of vscode.

**Comment by sukumo28** [comment]
Thank you for reporting.

Direct link to this extension is here.
https://marketplace.visualstudio.com/items?itemName=sukumo28.wav-preview

... or, you can find this extension on the marketplace by searching for the word `wav`, `sound`, `audio` and so on.
https://marketplace.visualstudio.com/search?term=wav&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by dqqcasia** [comment]
Unable to install extension 'sukumo28.wav-preview' as it is not compatible with VS Code '1.56.0'.

**Comment by dqqcasia** [comment]
Thank you for your reply.

Actually I need to use `vsix` file to install on the vs code server, and I encountered some problems. The error message is:

> Unable to install extension 'sukumo28.wav-preview' as it is not compatible with VS Code '1.56.0'. 

I have tested these versions, [v1.7.0](https://github.com/sukumo28/wav-preview/releases/tag/v1.7.0), [v1.6.0](https://github.com/sukumo28/wav-preview/releases/tag/v1.6.0) and [1.5.0](https://github.com/sukumo28/wav-preview/releases/tag/v1.5.0) for `wav-preview`.

Do you have any suggestion?

**Comment by dqqcasia** [comment]
> Thank you for your reply.
> 
> Actually I need to use `vsix` file to install on the vs code server, and I encountered some problems. The error message is:
> 
> > Unable to install extension 'sukumo28.wav-preview' as it is not compatible with VS Code '1.56.0'.
> 
> I have tested these versions, [v1.7.0](https://github.com/sukumo28/wav-preview/releases/tag/v1.7.0), [v1.6.0](https://github.com/sukumo28/wav-preview/releases/tag/v1.6.0) and [1.5.0](https://github.com/sukumo28/wav-preview/releases/tag/v1.5.0) for `wav-preview`.
> 
> Do you have any suggestion?

Sorry, I just found out that version [1.2.0](https://github.com/sukumo28/wav-preview/releases/tag/v1.2.0) can be used.

Thanks again!
