### ISSUE TITLE
Add an option to display the spectrogram

### ISSUE THREAD

**Issue by rayandaod** [sukumo28/wav-preview#24]
As an Audio Machine Learning enthusiast, I love your extension. It saves me so much time when I want to quickly listen to an input or output audio.

Being able to display the spectrogram would be a massive upgrade as we would have an even better feeling of what the audio is composed of. No need for it to be too complex, here is an example: (taken from Adobe Audition)
![image](https://user-images.githubusercontent.com/15997013/149978962-6ae4b26a-79f1-469f-9895-d926e2a6ce4f.png)
It could be located below or on the right side of what already exists.

Bonus: add a thin vertical bar on the spectrogram acting as a cursor to easily keep track while listening.

**Comment by sukumo28** [comment]
you can preview spectrogram from v1.10.0.
thank you!

**Comment by rayandaod** [comment]
That's awesome thank you!! In a future update that would be great to also have time and amplitude information as x and y axis 💯
