### ISSUE TITLE
Display the waveform

### ISSUE THREAD

**Issue by rayandaod** [sukumo28/wav-preview#25]
Displaying the waveform will give more information about the shape, transients, energy, ... in a recording.
It would be convenient to have a moving cursor while playing, and to be able to position it wherever we want by clicking on the audio signal.

Example from Adobe Audition:
![image](https://user-images.githubusercontent.com/15997013/149981479-1b846ccd-7417-419f-b765-7967c8155621.png)

Example from Soundcloud:
![image](https://user-images.githubusercontent.com/15997013/149981609-d7a2df9e-a2d4-4027-9f05-0f59cd52d1c0.png)

**Comment by sukumo28** [comment]
you can preview waveform from v1.10.0.
thank you!

**Comment by rayandaod** [comment]
That's awesome as well, thanks a lot :) In a future update that would be great to also have time and amplitude information as x and y axis 👍🏽
