### ISSUE TITLE
Make the seek bar the same size as the spectrogram and waveform

### ISSUE THREAD

**Issue by rayandaod** [sukumo28/wav-preview#26]
The seek bar is great! It would be even better if it had the same size as the spectrogram and the waveform to easily match what we hear to what we see. Also, I don't know if this is because it is a constraint but if the seek bar cursor could refresh its position more often that would be very good for overall smoothness. Thank you for your work I love it!

**Comment by sukumo28** [comment]
seekbar on waveform and spectrogram and more frequent seekbar position update is implemented from v1.11.2
thank you for reporting
