### ISSUE TITLE
Add user control over the spectrogram parameters

### ISSUE THREAD

**Issue by rayandaod** [sukumo28/wav-preview#27]
Hello again :)
Another idea is to add more user control over the spectrogram parameters, e.g frame length, hop length, amplitude clipping (min, max), ...
It could also allow users to specify appearance/look parameters, e.g the color of the waveform.
Finally, it would be great to be able to set some default parameters, such as always_display_waveform, always_display_spectrogram, ...
One way would be to add a json file or some other configuration file modified by the user.
Have a great day!

**Comment by sukumo28** [comment]
user control on spectrogram and auto analyze option is added from v1.11.2.
thank you for reporting

**Comment by huskyachao** [comment]
Hi, Can I ask where to set the settings mentioned above? Is there any doc to introduce and explain the settting parameters?
