### ISSUE TITLE
Add amplitude values in the waveform view

### ISSUE THREAD

**Issue by rayandaod** [sukumo28/wav-preview#28]
Currently, it seems like the displayed waveform shape is normalized to the height of the waveform box, so we don't have any information on the loudness of the audio except if we listen to it.

It would be great to have the amplitude values on the left in the waveform plot, and if the shape height was **not** normalized :)

**Comment by sukumo28** [comment]
Thank you for reporting.
from next update, waveform does not normalized and you can change figure's Y axis min & max amplitude (default is -1, 1 but data is no longer normalized).

![waveform-view-change](https://user-images.githubusercontent.com/59384202/152356931-de5559b4-26cc-45bc-a3a3-679632ee2940.png)
