### ISSUE TITLE
Add default waveform amplitude range

### ISSUE THREAD

**Issue by rayandaod** [sukumo28/wav-preview#30]
It would be great to be able to set a default min/max for the waveform amplitude range, e.g -1,1.
Thank you again for your amazing work!

**Comment by sukumo28** [comment]
You can set default values of analyze settings with `settings.json` from v1.11.6 like below.
```json
"WavPreview.analyzeDefault": {
        "minAmplitude": -1,
        "maxAmplitude": 1,
    }
}
```
thank you!
