### ISSUE TITLE
More granularity in the spectrogram levels

### ISSUE THREAD

**Issue by rayandaod** [sukumo28/wav-preview#32]
It would be great to have more levels of energy than {dark, blue, light blue, white} to represent the energy level at each time-frequency bin.

For example,

![image](https://user-images.githubusercontent.com/15997013/153757308-ab6d6d16-af28-47a5-ad30-5fc6140dff83.png)

Also, it would be very convenient to be able to add a default range of spectrogram amplitudes, so that "white" always mean the same level in dB (not sure this is the case right now).

Thank you for your awesome work!

**Comment by sukumo28** [comment]
* use more colors to display levels of energy
* spectrogram amplitude setting
is supported from v1.12.0. (It's ) 
Thank you.
