### ISSUE TITLE
Spectograms 

### ISSUE THREAD

**Issue by rubbervduck** [sukumo28/wav-preview#64]
Hi there,

I hope you're doing well. I'm currently working on my capstone project and have been struggling to create spectrograms that meet the same quality as the ones generated by your audio preview extension. I was wondering if you could kindly share the code you used to create these spectrograms.

Great product, by the way—kudos to the entire team!

Thank you in advance for your help.

**Comment by sukumo28** [comment]
Yes, you can use the code in this project to display the spectrogram.

The spectrogram is drawn by this Component.
A Canvas is used to display the X-axis, Y-axis, and spectrogram.
They are drawn on separate Canvases of the same size and displayed on top of each other.
https://github.com/sukumo28/vscode-audio-preview/blob/main/src/webview/components/spectrogram/spectrogramComponent.ts

The data to display in the spectrogram is created in this Service.
The getSpectrogram method creates the spectrogram data.
The getSpectrogramColor determines the color of each pixel in the spectrogram.
https://github.com/sukumo28/vscode-audio-preview/blob/main/src/webview/services/analyzeService.ts

However, please be careful. I am not an expert in audio processing, so please keep in mind that the Spectrogram display code in this project may contain fatal errors when deciding whether to use it.
If you want more accurate code, the following projects are a good reference:
https://github.com/audacity/audacity

**Comment by rubbervduck** [comment]
Hey there,

I just wanted to say a huge thank you for sharing your resources. I really appreciate your support!

**Comment by sakshamsingh1** [comment]
I believe the python implementation for similar spectrogram might be helpful (for anyone interested).

```
import matplotlib.pyplot as plt
import numpy as np
import librosa
import librosa.display

# Load an example audio file
path = <AUDIO_PATH>
y, sr = librosa.load(path, sr=16000, duration=10)  # Load 10 seconds of audio at 16 kHz

# Define spectrogram parameters
n_fft = 1024  # Window size of 1024
hop_length = 512  # Overlap of 50%
fmin = 0  # Minimum frequency
fmax = 8000  # Maximum frequency
amplitude_range = (-90, 0)  # dB range

# Compute the spectrogram
S = np.abs(librosa.stft(y, n_fft=n_fft, hop_length=hop_length))
S_db = librosa.amplitude_to_db(S, ref=np.max)

# Plotting the spectrogram
plt.figure(figsize=(12, 5))
img = librosa.display.specshow(S_db, sr=sr, hop_length=hop_length, x_axis='time', y_axis='linear', 
                               fmin=fmin, fmax=fmax, cmap='magma', vmin=amplitude_range[0], vmax=amplitude_range[1])
plt.colorbar(format='%+2.0f dB').set_label("Amplitude (dB)", labelpad=20, rotation=270)

# Labels and title
plt.xlabel("Time (s)")
plt.ylabel("Frequency (Hz)")
plt.title("Spectrogram")
plt.tight_layout()
plt.show()

```

**Comment by rubbervduck** [comment]
Hey, thank you for the advice.

We were initially using Librosa, but our mentor wasn't happy with the quality of the spectrogram for the reports. So, we reached out to the admin to help us out.

By the way, great personal website! It's simple and appealing. I might use it as a reference to make changes to mine.

**Comment by sakshamsingh1** [comment]
Hi,

I found that we can make similar quality spectrograms using the python code above. 

Also, thanks and please feel free to use the website template.
