### ISSUE TITLE
[Feature Request] Adding more WAV header fields

### ISSUE THREAD

**Issue by xhamyd** [sukumo28/wav-preview#7]
Hi, thank you for sharing this extension! Happened to be recommended this viewer/player of WAV files in VSCode, has been super useful! I especially love the fact that the sample rate, number of channels, number of samples, and duration are listed in a quick reference table.

Related to this, I was wondering if it might be possible to add some more fields in here as it relates to wav files. Things like the bit depth (16bit, 32bit, etc.) and the format (PCM, mu-law, etc.) would really help in viewing the most important parts of the wav header. If it's encouraged or helpful, I can also volunteer to work on this in a new PR if possible.

Thanks again for this extension, and let me know if it's possible!

**Comment by sukumo28** [comment]
That's a good idea.  If possible, please send a PR.

**Comment by sukumo28** [comment]
I added `bit depth`, `compress formats`, and some other headers!  
It's available v1.4.0~.  

Since I changed decoder, now I can easily add more detailed info to the table such like `cue point`, `fact`, and so on.  
Please feel free to open issue or send pull request about that.
